### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by ccicchitelli** [MichMich/MagicMirror#1171]
Never mind, looks like this isn't an issue on Linux, only Windows. Still likely worth an update though...

**Comment by MichMich** [comment]
The new electron has issues on the Raspberry Pi. Mainly CPU issues. 

Due to the fact that in this project electron is nog loading any remote sites, the risk is less severe than described. 

That being said, I agree we need to switch do the new version. But this can only be done when electron solves their issues on the RaspPi platform. 

Fyi: the develop branch does run the latest electron version, so we can test the most recent version and hopefully incorporate it the next master branch.
