### ISSUE TITLE
Black screen [electron]

### ISSUE THREAD

**Issue by parsons12** [MichMich/MagicMirror#1319]
Magic Mirror opens to a blank black screen. All modules are default. It was working before but now when it opens the tab says “[Electron]” and displays a blank screen. I tried downgrading the electron version as suggested but it still does not work.

**Comment by MichMich** [comment]
Thanks for opening an issue!

To allow us to help you it's extremely important that we have all the details about your setup. During the creation of this issue, important details were asked to fill in. Because you did not provide (any) of these details we are unable to help you. 

If you are running into errors, please provide as many detailed error logs as possible in addition to the requested details.

If you are unaware how to retrieve all the requested information, feel free to ask for help on http://forum.magicmirror.builders.

This issue will be closed. Feel free to open a new issue with all the requested information.
