### ISSUE TITLE
npx: the better npm?

### ISSUE THREAD

**Issue by justjim1220** [MichMich/MagicMirror#1558]
Not really an issue, but a possible update for future versions of MM???

I am thinking this could cut down the size of the total application of MM plus any modules created that use node_modules as they wouldn't have to be added to any modules that have dependencies. You would have the original set within MM and any modules requiring the use of any of the dependencies wouldn't need to duplicate the folder within them. Thus, cutting down on the total size of MM plus modules, which in turn should help MM run smoother and faster. 

As, I was always taught: The shorter and cleaner the code, the smoother and faster the application.

Just a thought... :)

**Comment by MichMich** [comment]
To keep thinks simple, I think it's best to stick to well known tools. Since MagicMirror² is meant as an application running on a dedicated Pi, size isn't really an issue. 

Please read the manifesto on why I prefer well known solutions: https://github.com/MichMich/MagicMirror#manifesto

Closing this for now. Thanks.
