### ISSUE TITLE
Weather min/max temperature calculations

### ISSUE THREAD

**Issue by tisnatch** [MichMich/MagicMirror#1694]
I've been tearing my hair out trying to understand why the highs and lows shown in the 5-day forecast in the weather module differ from that of the 5-day forecast on the openweathermap website. I think I understand it now and would like to make a suggestion. 

It seems that the daily low is typically defined in weather forecasts as the low temperature for today's evening or TOMORROW's early morning (i.e. the overnight low). That much is becoming clear after doing some research. So, to calculate the daily low for today you might ignore the early hours of the day (e.g. 00:00 - 08:00) and you would include those same hours for the next day in your calculation. 

I can't find as much information on how daily highs are calculated though. But from looking at the weather forecast on the openweathermap website and comparing it to the JSON from the API it seems like the forecasted high is based on the high temperature before sunset, or at least some arbitrary time in the afternoon. As an example, for my city, this Saturday's high is supposed to be around 76 (in freedom units). This is plus or minus a couple degrees for the different forecast sites (darksky, NOAA, openweathermap, weather channel). However, the weather module is calculating Saturday's high to be 83 because that temperature occurs in the early evening. It seems weather forecasts typically take the high temperature that occurs before 16:00, for example. 

All that to say: I think the weather module should calculate min/max the same way other forecasting sites do. Otherwise it just feels like the weather module forecasts are incorrect when every other available forecast contradicts it. I would do it myself and contribute but you guys are WAY ahead of me in writing decent code. I would just screw it up, or at the very minimum create a mass of tangled spaghetti code.

**Comment by vincep5** [comment]
Interesting points, you seem to be correct.  It looks like OpenWeatherMap takes the afternoon temperature as the daily high (1pm-4pm) and the next days morning low (1am-4am) as the daily low.   For my town it just picks the 1pm and the 1am temps and puts that as the high/low.  But when I look at other cities outside the US, it does not follow that exact pattern.  I don't know how exactly they are doing it.  Unless we can figure it out exactly, there will always be a few degrees difference from MM to the website.

OpenWeatherMap also has 2 APIs - so each has its own logic.  The /forecast/daily API we could use the "day" and "night" properties as those values are what are displayed on the website and not "min" and "max".  That is a simple change.

But even so, changing that doesn't help the users that use the /forecast API.  This is the majority of users as this is the free one.  It provides 3 hour intervals in which the MM code determines the max and min based on the objects it iterates through.

DarkSky looks a different.  They take the daily high and low based on the day's full 24 hours.  So that one is straightforward and the code today is accurate.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
