### ISSUE TITLE
Issues with Weather Tests. - Tests currently disabled.

### ISSUE THREAD

**Issue by MichMich** [MichMich/MagicMirror#1840]
For some unknown reason most of the weather module tests seem to fail (both on Travis as well as local) due to timeout issues. To be able to continue the development I have disabled the weather tests by adding a skip statement: https://github.com/MichMich/MagicMirror/blob/develop/tests/e2e/modules/weather_spec.js#L18

This means the weather tests are currently not used. This could impact the quality of the code. I can't seem to find any reason why these tests time out. 

If anyone is able to solve this issue and get travis to successfully complete the tests, please send a PR. Your contribution would be highly appreciated.

Thanks!

**Comment by roramirez** [comment]
After merge #1849 I could check it

**Comment by MichMich** [comment]
Fixed by reverting electron. See https://github.com/MichMich/MagicMirror/issues/1800

**Comment by sdetweil** [comment]
still failing today

**Comment by MichMich** [comment]
They run ok now. They timeout after 10sec. We might need to stretch that 10 sec.

**Comment by sdetweil** [comment]
The code says if under CI then timeout is 30 seconds

**Comment by MichMich** [comment]
This line (for example) uses 10000ms:
https://github.com/MichMich/MagicMirror/blob/69a887fb05af79071eb20875c1c4a856627f7811/tests/e2e/modules/weather_spec.js#L48

**Comment by sdetweil** [comment]
Ok. Other tests call a function in global_setup to set timeouts. Figured they all would

**Comment by roramirez** [comment]
I've try catch the failed of this and  apparently is because is too slow to run these tests. There a other line
https://github.com/MichMich/MagicMirror/blob/69a887fb05af79071eb20875c1c4a856627f7811/tests/e2e/modules/weather_spec.js#L11
for a wait. Maybe @fewieden can check a look of this.

**Comment by fewieden** [comment]
@roramirez @MichMich I tried this morning the newest version of develop and run the tests locally, they all passed after ~7s.

What is the setup I need to reproduce the issue?

Since this seems to be still relevant, we should reopen the issue.

**Comment by roramirez** [comment]
Hi @fewieden 

You should try into a similar environment where is running like Travis. Maybe you can using the follow guide (I'm use this one) https://jonlabelle.com/snippets/view/markdown/run-travis-ci-builds-locally-with-docker.

Or also requests the debug mode for your Fork in Travis 
https://docs.travis-ci.com/user/running-build-in-debug-mode/#enabling-debug-mode

> Since this seems to be still relevant, we should reopen the issue.

Yes. Should reopen this issue

**Comment by roramirez** [comment]
@fewieden I forget other thing. Also should run the test against the PR https://github.com/MichMich/MagicMirror/issues/1840

**Comment by fewieden** [comment]
@roramirez the PR that you tried to reference is a link to this issue.

Therefore I tried https://jonlabelle.com/snippets/view/markdown/run-travis-ci-builds-locally-with-docker to debug this [commit](https://github.com/MichMich/MagicMirror/commit/c1e808bce66ec1d8e937f5dac91f2ca6f695e8de) which had the original build [log](https://travis-ci.com/MichMich/MagicMirror/builds/142541536).

Executing the tests inside the docker container resulted in a different error

![Capture](https://user-images.githubusercontent.com/9334168/73609625-e920a900-45cf-11ea-8076-06e28d5d47db.PNG)

What I found is https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t but even with adding all those argumens to the chrome driver the issue still appeared. Maybe I passed them wrong?

Running the tests locally gives a third result. Sometimes they pass, sometimes the same tests fail. I could see that they made actual requests to the api server instead of using the mock. Maybe we have a timing iue in there.

Updating electron and spectron to their latest stable versions is passing all the [tests](https://travis-ci.com/fewieden/MagicMirror/builds/147096746). What is failing, is the npm list command afterwards.

![Capture](https://user-images.githubusercontent.com/9334168/73609877-179f8380-45d2-11ea-8f4a-54504903c187.PNG)

CC @MichMich

**Comment by roramirez** [comment]
Hi @fewieden You're right. I've reference wrong the  PR. This should be #1892. Sorry for that. This change is already merge in `develop` you could try against this branch. The test for weather is disabled in this branch.

The problem you are getting is because the sandbox mode is enable by default. More information about this is  #1892

Setting  the enviroment variable `ELECTRON_DISABLE_SANDBOX=1`  before run the test should be enough.

**Comment by fewieden** [comment]
@roramirez looks like I found the issue

**Comment by roramirez** [comment]
@fewieden Nice work!. Seems there this was little trickle but you found it.

@MichMich You should merge the #1927

**Comment by MichMich** [comment]
Merged!
