### ISSUE TITLE
Install script hangs on some systems doing apt-get upgrade

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#1866]
updated install script prompts for y/n to continue on some systems. 

stdout redirected to file, so user can't see it.

**Comment by LeviDavisCode** [comment]
hey did you have any luck getting it to work? I have the same problem

**Comment by sdetweil** [comment]
@LeviDavisCode 
yes, use the updated script, see the external script repo for the new url

https://github.com/sdetweil/MagicMirror_scripts

**Comment by vkramsingh** [comment]
Hi,
I used the external script url but my installation is still stuck at apt-update. The last line in the log file is apt-get update completed ok

**Comment by sdetweil** [comment]
@vkramsingh 
please use the install script from  here
https://github.com/sdetweil/MagicMirror_scripts

**Comment by MichMich** [comment]
FYI, The link to (broken) the install script is removed from the README.md.

**Comment by tbouron** [comment]
Experienced the same issue when I reinstalled my mirror this weekend. It's because the script uses `sudo` to run the majority of commands. But for some reason, the script does not prompt for the password, hence the hang.

Once you run at least once command with `sudo` before hand, the password is cached and the script will work fine.

I don't know if this is a regression or not, last time it worked fine but I might have used `sudo` prior to executing the script.

**Comment by sdetweil** [comment]
the newer updated script does handle this..   the new doc points to the alternate install sites

**Comment by sdetweil** [comment]
I am closing this, link to new site 
https://github.com/sdetweil/MagicMirror_scripts
