### ISSUE TITLE
Weather forecast ignores "maxNumberOfDays"

### ISSUE THREAD

**Issue by mirko3000** [MichMich/MagicMirror#2018]
Hi there,

currently the config parameter "maxNumberOfDays" of the module "weatherforecast" seems to be ignored - at least it does not work increasing it to more than 7 days. That is because the API needs an additional parameter "cnt", which indicates how many days are to be retrieved. Adding it to the weatherforecast.js in line 305 solves the issue for me:

`params += "&cnt=" + this.config.maxNumberOfDays;`

Best regards,
Mirko

**Comment by MichMich** [comment]
Please send a PR.

Thanks!

**Comment by hangorazvan** [comment]
params += "&cnt=" + (((this.config.maxNumberOfDays < 1) || (this.config.maxNumberOfDays > 128)) ? 40 : this.config.maxNumberOfDays);

**Comment by rejas** [comment]
Maybe add a "Good first bug" to this Issue so people who want to start helping can fix it? Otherwise I will do it sooner than later ;-)

**Comment by Ekristoffe** [comment]
> 
> 
> `params += "&cnt=" + (((this.config.maxNumberOfDays < 1) || (this.config.maxNumberOfDays > 128)) ? 40 : this.config.maxNumberOfDays);`

I the documentation it said:
```
How many days of forecast to return. Specified by config.js

Possible values: 1 - 16
Default value: 7 (7 days)
This value is optional. By default the weatherforecast module will return 7 days.
```
I think only a limit of 16 would be nice.
And i don't think anyone need a forecast of more than 16 days.

**Comment by sdetweil** [comment]
>And i don't think anyone need a forecast of more than 16 days.

and more importantly, can you GET  a forecast from any api for more that 15 days?

**Comment by Ekristoffe** [comment]
Well I can make it work up to 17  after there is no answer.

**Comment by lavolp3** [comment]
Still seems to be an issue
https://forum.magicmirror.builders/topic/13187/weatherforecast-showing-only-two-days/6

**Comment by ember1205** [comment]
I wanted to add a comment here that this issue is not actually "fixed" as the new version now reverts forecasts back to showing only two days (at least when using the Free API). In doing some research, it appears that the actual URL being used to retrieve the forecast is not the correct / current one.

From what I can tell, the base URL is being built out as:

`https://api.openweathermap.org/data/2.5/forecast??id={id}&appid={API key}`

According to the API docs, it should be built out as:

`https://api.openweathermap.org/data/2.5/onecall?lat={lat}&lon={lon}&exclude={part}&appid={API key}`
