### ISSUE TITLE
Suggestion: config.js.sample Change

### ISSUE THREAD

**Issue by BKeyport** [MichMich/MagicMirror#2653]
I've noticed a lot of issues on the forum reference the port MM uses.

Currently, in the config.js.sample, you simply have: 
```
port: 8080, 
```

I would recommend changing it to this: 

```
port: 8080, // We suggest changing this port, 60000-61000 is generally safe, this is to avoid conflicts. 
```

**Comment by MichMich** [comment]
In most cases there is no need to change this. Most users have one dedicated Pi for the Mirror and there are no default services running on 8080. If someone stumbles into an issue due to an other app running on 8080, they can always change it. But let's not make it complicated by default for some edge cases.
