### ISSUE TITLE
Calendar: Multiday events always starts at current day

### ISSUE THREAD

**Issue by buxxi** [MichMich/MagicMirror#2685]
In my calendar I have an event that spans from this tuesday to sunday, now on thursday it displays it as (1/4) instead of (3/6).
It also broadcasts to another module with the startDate being midnight for the current day. So I would guess some display logic is modifying the original data?

My config:
```
		{
			module: "calendar",
			position: "top_left",
			config: {
				displaySymbol: false,
				maximumEntries: 100,
				hideOngoing: false,
				broadcastPastEvents: true,
				sliceMultiDayEvents: true,
				calendars: [
					{
						color: "#55acee",
						url: "https://calendar.google.com/...REDACTED"
					}
				]
			}
		},
```

It's in a private calendar but here's the relevant event:
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20211012
DTEND;VALUE=DATE:20211018
DTSTAMP:20211014T154936Z
UID:REDACTED@google.com
CREATED:20211001T101108Z
DESCRIPTION:
LAST-MODIFIED:20211001T101109Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:International 10
TRANSP:TRANSPARENT
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT3H0M0S
END:VALARM
END:VEVENT
```

**Comment by jupadin** [comment]
This is the intended behavior.
@sdetweil commented on this in https://github.com/MichMich/MagicMirror/issues/2629#issuecomment-901983877.
For a multi day event, the current day instead of the start of the event is used (and we then don't know when the event has started - could be yesterday or the day before yesterday - but we use the current day as the beginning of the event).
Hope the link and the short answer helps...
