### ISSUE TITLE
clock module shows 1 week wrong. think it uses calendar for 2020

### ISSUE THREAD

**Issue by paarak** [MichMich/MagicMirror#2713]
"version": "2.17.1",

![magicmirror weeknumber](https://user-images.githubusercontent.com/56606692/142425816-1dc1124b-9302-4ccf-9834-750649f6c570.png)

**Comment by rejas** [comment]
Hi, could you please post your clock entry from the config.js so we can take a look?

**Comment by MichelBarneveld** [comment]
Change the language in your config.js to "en-gb" (British English) if you want to have the interface in English and you are in europe, instead of "en" (United States English). It will show the correct week. 

That is because there is an ISO standard for the first week of the year and some countries like the US not following that standard ;-) 
Moment.js uses the locale information to determine which method to use for weeknumbers.

For most countries the first week of the year is the first week with 4 days in the new year, like in Europe.
However there are some countries that uses the first week that has the first day of the year in it, like the US.

So this year the first day of the year was on a friday. Since Friday, Saturday and Sunday are only 3 days, the first week of this year started on Monday 4th of January in most countries. However in the US that was already week 2, since the first day of the year was the week before on Friday. So the US is 1 week ahead on Europe this year.

See also: https://en.wikipedia.org/wiki/ISO_week_date#First_week
and: https://en.wikipedia.org/wiki/ISO_week_date#Other_week_numbering_systems

**Comment by paarak** [comment]
![image](https://user-images.githubusercontent.com/56606692/143734523-d879de95-d2f5-4675-beeb-49385d3616cb.png)

**Comment by paarak** [comment]
> Hi, could you please post your clock entry from the config.js so we can take a look?

![image](https://user-images.githubusercontent.com/56606692/143734523-d879de95-d2f5-4675-beeb-49385d3616cb.png)
