### ISSUE TITLE
Missing "," in logger.js Line 34

### ISSUE THREAD

**Issue by BoxSo** [MichMich/MagicMirror#277]
Caused some trouble here, getting V2 to work. At the end it was a missing "," in Line 34 in logger.js :)

Regards

Jens

**Comment by KirAsh4** [comment]
Good catch. I went ahead and created a pull request.

**Comment by MichMich** [comment]
Ah, missed your PR. Fixed already.

**Comment by KirAsh4** [comment]
I had just done a fresh fork and sync to my system and scratched my head wondering what happened ... then I saw his post and went 'oh duh!' ... had to PR it. :)

And of course because of a rather stupid error on my part, I need to resync again. *sigh* Some days I hate a) Git, b) GitHub, c) having multiple machines, d) developing on a machine that's different than what's I'm sitting at ... #FirstWorkdProblems #potverdorie
