### ISSUE TITLE
Feature Request: Add Photobooth Module

### ISSUE THREAD

**Issue by 1WickedOne** [MichMich/MagicMirror#3037]
There are commercial versions of magic mirrors with photobooth option built in and was surprised there wasn't a module for a Photobooth in MagicMirror2.

**Comment by sdetweil** [comment]
this is up to the user/community to build... not part of the base.

**Comment by rejas** [comment]
I agree with @sdetweil this sounds more like a 3rd party module then a necessary base module. 

Closing this since it is obviously not a feature we will do in core. 

Please ask in the forum if you need a module like this or take a look at https://github.com/MichMich/MagicMirror/wiki/3rd-Party-Modules if there is something for your needs.
