### ISSUE TITLE
Null displayed using Microsoft EDGE browser 

### ISSUE THREAD

**Issue by benjeefox** [MichMich/MagicMirror#319]
**Platform** 
Raspberry Pi 2 as serveronly
Browser client Microsoft EDGE from Windows 10

**Node Version**
v5.9.1

**MagicMirror Version** 
v2-beta

**Description:** 
While browsing MM2 on Microsoft EDGE, some NULL are displayed in each module

For screenshot:
[https://forum.magicmirror.builders/topic/78/null-displayed-using-microsoft-edge-browser](url)

**Comment by KirAsh4** [comment]
I don't want you to think this is being ignored. I see it too on my end ... I just don't use Edge but I don't expect everyone to do that. :)

I'm working on some other code (and different projects), but i will try to find some time and dig into this. One of the immediate things that comes to mind is that the Edge browser is still very new and doesn't have the same compatibility as the more mature browsers (I use Chrome, Firefox, and Internet Explorer, in that order of preference), so it's likely this is something with the browser itself that we can't do anything about. However, nothing is for sure till we investigate.

Just as an FYI, on a Windows 10 machine, you do still have Internet Explorer, they just hide it. But you can still use that instead of the newer Edge browser.

**Comment by cschwarz007** [comment]
Note I have the same issue (diesplaying "null") in IE11 on my Win10 machine. But I can confirm the issue does not appear with Google Chrome (on Win 10). See attached screenshot for examples...

![unbenannt](https://cloud.githubusercontent.com/assets/20018714/16173603/1522d8d0-35a7-11e6-8c43-2c650483b69d.PNG)

**Comment by KirAsh4** [comment]
Yes, this is specific to Edge. Being that it's a new browser, there is still a lot missing in it. Use Internet Explorer instead (yes it is installed, you aren't forced to use Edge.)

**Comment by KirAsh4** [comment]
This has now manifested itself in the most recent version of Microsoft Explorer as well. I tracked it down and submitted a PR for it, #366 ...

**Comment by KirAsh4** [comment]
@benjeefox and @cschwarz007, have you had a chance to pull the dev branch and test this, see if the bug still exists?

**Comment by cschwarz007** [comment]
Hi, I can confirm PR #366 fixes the issue... Thanks a lot!

**Comment by ljw98** [comment]
hello,i want to know how can i run this in windows10 with Google Chrome

**Comment by justjim1220** [comment]
Node serveronly

**Comment by sindhuja1999** [comment]
how to get access token and bearer authentication in smart mirror?
