### ISSUE TITLE
Git ignore file...

### ISSUE THREAD

**Issue by Snille** [MichMich/MagicMirror#90]
Hi, I love the clean look of the "mirror".
It would be great if you added a .gitignore file ignoring the changes made in the config.js file locally.
When pulling the config.js file get's overwritten. :)

Thank you for sharing!

**Comment by wcdanh2** [comment]
You can also ignore the config.js file on your end by adding it to .git/info/exclude  This will allow you to use "git add ." while still skipping changes to the config.js  (This is great for making a pull request back to the main branch.)

I expect that config.js will change its form in the future so when making a commit it will probably be best to cherry-pick the rather than ignore it completely.

**Comment by Snille** [comment]
Ah, thank you. I'll do that. good to know. :)
